version: '3'
services:
    app:
        image: "nkt929/lab41"
        ports:
            - "8080:8080"
    nginx:
        image: "nginx:alpine"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./media:/www/media
        depends_on: 
            - app
        ports:
            - "80:80"